runtime: python39  # or python38, depending on your environment

entrypoint: gunicorn -b :$PORT main:app

# Optional: automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 2
  min_instances: 1
